language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

cache: pip

install:
  - pip install -U -r requirements/base.txt
  - pip install -U -r requirements/test.txt
  - pip install pytest-cov

script:
  - py.test --cov=./

notifications:
  email: false
