language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

cache: pip

install:
  - pip install -U -r requirements/base.txt
  - pip install -U -r requirements/test.txt

script:
  - python -m pytest

notifications:
  email: false
